SELECT 
WEBSITE_SESSION.UTM_CONTENT,
COUNT(DISTINCT WEBSITE_SESSION.WEBSITE_SESSION_ID) AS SESSION,
COUNT(DISTINCT ORDERS.ORDER_ID) AS ORDERS,
COUNT(DISTINCT ORDERS.ORDER_ID)/COUNT(DISTINCT WEBSITE_SESSION.WEBSITE_SESSION_ID) AS CONVERSION_RATE 
FROM WEBSITE_SESSION
LEFT JOIN ORDERS
ON ORDERS.WEBSITE_SESSION_ID = WEBSITE_SESSION.WEBSITE_SESSION_ID 
WHERE WEBSITE_SESSION.CREATED_AT BETWEEN '2014-01-01' AND '2014-02-01'
GROUP BY 1
ORDER BY session DESC;
;
    
    
    
    
---- ASIGNMENT 1
SELECT 
MIN(DATE (CREATED_AT)) AS week_START,
COUNT(CASE  WHEN UTM_SOURCE ='gsearch' then WEBSITE_SESSION_ID else NULL END) AS gsearch_session,
count(case when UTM_SOURCE = 'bsearch' THEN WEBSITE_SESSION_ID  ELSE NULL END)AS  bsearch_session

FROM WEBSITE_SESSION
WHERE CREATED_AT BETWEEN '2012-08-22' AND '2012-11-29'
and UTM_CAMPAIGN = 'nonbrand'
group by WEEKOFYEAR(CREATED_AT) 
;    

---- ASSIGNMENT 2
SELECT  
UTM_SOURCE,
COUNT(DISTINCT WEBSITE_SESSION_ID) AS SESSION,
COUNT(CASE WHEN DEVICE_TYPE = 'mobile' THEN WEBSITE_SESSION_ID ELSE NULL END ) AS MOBILE_SESSION,
COUNT(CASE WHEN DEVICE_TYPE = 'mobile' THEN WEBSITE_SESSION_ID ELSE NULL END ) /COUNT(DISTINCT WEBSITE_SESSION_ID) AS PCT_MOBILE 
FROM WEBSITE_SESSION
WHERE CREATED_AT BETWEEN '2012-08-22' AND '2012-11-29'
and UTM_CAMPAIGN = 'nonbrand'
AND UTM_SOURCE IN ('bsearch','gsearch')
GROUP BY 1
;
    
------------ ASSIGNMENT 4

SELECT 
WEBSITE_SESSION.DEVICE_TYPE,
WEBSITE_SESSION.UTM_SOURCE,
COUNT(DISTINCT WEBSITE_SESSION.WEBSITE_SESSION_ID) AS SESSION,
COUNT( DISTINCT ORDERS.WEBSITE_SESSION_ID) AS ORDERS ,
COUNT( DISTINCT ORDERS.WEBSITE_SESSION_ID)/COUNT(DISTINCT WEBSITE_SESSION.WEBSITE_SESSION_ID) AS CONV_RATE
FROM WEBSITE_SESSION
LEFT JOIN ORDERS 
ON ORDERS.WEBSITE_SESSION_ID = WEBSITE_SESSION.WEBSITE_SESSION_ID
WHERE WEBSITE_SESSION.CREATED_AT BETWEEN '2012-08-22' AND '2012-09-18'
and WEBSITE_SESSION.UTM_CAMPAIGN = 'nonbrand'
  GROUP BY 1,2 
    ;
    
------ ASIIGNMENT 5
SELECT 
MIN(DATE(CREATED_AT)) AS WEEK_START_DATE,
COUNT( CASE WHEN UTM_SOURCE = 'gsearch' AND DEVICE_TYPE='desktop' THEN WEBSITE_SESSION_ID ELSE NULL END )AS g_dtop_session,
COUNT( CASE WHEN UTM_SOURCE = 'bsearch' AND DEVICE_TYPE='desktop' THEN WEBSITE_SESSION_ID ELSE NULL END )AS b_dtop_session,
COUNT( CASE WHEN UTM_SOURCE = 'bsearch' AND DEVICE_TYPE='desktop' THEN WEBSITE_SESSION_ID ELSE NULL END )/
COUNT( CASE WHEN UTM_SOURCE = 'gsearch' AND DEVICE_TYPE='desktop' THEN WEBSITE_SESSION_ID ELSE NULL END ) as b_pct_of_g_dtop,
COUNT( CASE WHEN UTM_SOURCE = 'gsearch' AND DEVICE_TYPE='mobile' THEN WEBSITE_SESSION_ID ELSE NULL END )AS g_mobile_session,
COUNT( CASE WHEN UTM_SOURCE = 'bsearch' AND DEVICE_TYPE='mobile' THEN WEBSITE_SESSION_ID ELSE NULL END )AS b_mobile_session,
COUNT( CASE WHEN UTM_SOURCE = 'bsearch' AND DEVICE_TYPE='mobile' THEN WEBSITE_SESSION_ID ELSE NULL END) /
COUNT( CASE WHEN UTM_SOURCE = 'gsearch' AND DEVICE_TYPE='mobile' THEN WEBSITE_SESSION_ID ELSE NULL END ) as b_mob_of_gmob

FROM WEBSITE_SESSION
WHERE WEBSITE_SESSION.CREATED_AT BETWEEN '2012-11-04' AND '2012-12-02'
and WEBSITE_SESSION.UTM_CAMPAIGN = 'nonbrand'
   group by 
   week(created_at)
 ;   
    
    
    
    
 select distinct HTTP_REFERER FROM WEBSITE_SESSION;   
----------------------------------------------------------------------
SELECT 
CASE 
WHEN HTTP_REFERER IS NULL THEN 'direct_type_in'
when HTTP_REFERER = 'https://www.gsearch.com' THEN 'gsearch_organic'
when HTTP_REFERER = 'https://www.bsearch.com' THEN 'bsearch_organic'
else 'other'
end,
count(distinct website_session_id) as sessions
FROM WEBSITE_SESSION
group by 1
order by 2 desc;
    
    
------ ASSIGMENT
SELECT distinct
CASE 
WHEN UTM_SOURCE IS NULL AND  HTTP_REFERER IN ('https://www.gsearch.com','https://www.bsearch.com') THEN 'organic_search'
when UTM_CAMPAIGN = 'nonbrand' THEN 'PAIDNONBRAND'
when UTM_CAMPAIGN = 'brand' THEN 'PAID_BRAND'
WHEN UTM_SOURCE IS NULL AND HTTP_REFERER IS NULL THEN 'DIRECT_TTYPE_IN'
END AS CHANNEL_GROUP ,
UTM_SOURCE,
UTM_CAMPAIGN,
HTTP_REFERER
FROM website_session
where created_at < '2012-12-23'
;
    
    
SELECT 
WEBSITE_SESSION_ID,
CREATED_AT,
CASE 
WHEN UTM_SOURCE IS NULL AND  HTTP_REFERER IN ('https://www.gsearch.com','https://www.bsearch.com') THEN 'organic_search'
when UTM_CAMPAIGN = 'nonbrand' THEN 'PAIDNONBRAND'
when UTM_CAMPAIGN = 'brand' THEN 'PAID_BRAND'
WHEN UTM_SOURCE IS NULL AND HTTP_REFERER IS NULL THEN 'DIRECT_TTYPE_IN'
END AS CHANNEL_GROUP 

FROM website_session
where created_at < '2012-12-23'
;  
    
    
  SELECT YEAR(CREATED_AT) AS YR,
  MONTH(CREATED_AT) AS MONTH,
  COUNT(DISTINCT CASE WHEN CHANNEL_GROUP = 'PAIDNONBRAND' THEN WEBSITE_SESSION_ID ELSE NULL END) AS NONBRAND,
   COUNT(DISTINCT CASE WHEN CHANNEL_GROUP = 'PAID_BRAND' THEN WEBSITE_SESSION_ID ELSE NULL END) AS BRAND,
      COUNT(DISTINCT CASE WHEN CHANNEL_GROUP = 'PAID_BRAND' THEN WEBSITE_SESSION_ID ELSE NULL END)/
       COUNT(DISTINCT CASE WHEN CHANNEL_GROUP = 'PAIDNONBRAND' THEN WEBSITE_SESSION_ID ELSE NULL END) AS BRAND_PCT_OF_NONBRAND,
    COUNT(DISTINCT CASE WHEN CHANNEL_GROUP = 'DIRECT_TTYPE_IN' THEN WEBSITE_SESSION_ID ELSE NULL END) AS DIRECT,
    COUNT(DISTINCT CASE WHEN CHANNEL_GROUP = 'DIRECT_TTYPE_IN' THEN WEBSITE_SESSION_ID ELSE NULL END)/
    COUNT(DISTINCT CASE WHEN CHANNEL_GROUP = 'PAIDNONBRAND' THEN WEBSITE_SESSION_ID ELSE NULL END) AS DIRECT_PCT_NONBRAND,
     COUNT(DISTINCT CASE WHEN CHANNEL_GROUP = 'organic_search' THEN WEBSITE_SESSION_ID ELSE NULL END) AS DIRECT,
      COUNT(DISTINCT CASE WHEN CHANNEL_GROUP = 'organic_search' THEN WEBSITE_SESSION_ID ELSE NULL END) /
      COUNT(DISTINCT CASE WHEN CHANNEL_GROUP = 'PAIDNONBRAND' THEN WEBSITE_SESSION_ID ELSE NULL END)  AS ORGANIC_PCT_NONBRAND
  FROM(
  SELECT 
WEBSITE_SESSION_ID,
CREATED_AT,
CASE 
WHEN UTM_SOURCE IS NULL AND  HTTP_REFERER IN ('https://www.gsearch.com','https://www.bsearch.com') THEN 'organic_search'
when UTM_CAMPAIGN = 'nonbrand' THEN 'PAIDNONBRAND'
when UTM_CAMPAIGN = 'brand' THEN 'PAID_BRAND'
WHEN UTM_SOURCE IS NULL AND HTTP_REFERER IS NULL THEN 'DIRECT_TTYPE_IN'
END AS CHANNEL_GROUP 

FROM website_session
where created_at < '2012-12-23'
  
  ) AS SESSION_W_CHANNEL_GROUP
  GROUP BY
  YEAR(CREATED_AT),
  MONTH(CREATED_AT)
  ;
  
    
    
    
    
    
    
    
    
    
    
    
    
    
    
