USE Maven_Fuzzy_Factory;
select * from "MAVEN_FUZZY_FACTORY"."PUBLIC"."WEBSITE_SESSION"
where WEBSITE_SESSION_ID = 1059;

select * from "MAVEN_FUZZY_FACTORY"."PUBLIC"."WEBSITE_PAGEVIEWS"
where WEBSITE_SESSION_ID=1059;

select * from orders
where WEBSITE_SESSION_ID=1059;


SELECT WEBSITE_SESSION.UTM_CONTENT,
COUNT(DISTINCT WEBSITE_SESSION.WEBSITE_SESSION_ID) AS SESSIONS ,
COUNT(DISTINCT ORDERS.ORDER_ID) AS ORDERS,
COUNT(DISTINCT ORDERS.ORDER_ID)/COUNT(DISTINCT WEBSITE_SESSION.WEBSITE_SESSION_ID) AS SESSION_TO_ORDER_CONV_RT
FROM WEBSITE_SESSION
    LEFT JOIN ORDERS
            ON ORDERS.WEBSITE_SESSION_ID = WEBSITE_SESSION.WEBSITE_SESSION_ID

WHERE WEBSITE_SESSION.WEBSITE_SESSION_ID BETWEEN 1000 AND 2000
 
GROUP BY UTM_CONTENT
ORDER BY 2 DESC
;

SELECT * FROM WEBSITE_SESSION;


SELECT UTM_SOURCE,UTM_CAMPAIGN,HTTP_REFERER,
COUNT(DISTINCT WEBSITE_SESSION_ID)  AS SESSION
FROM WEBSITE_SESSION
WHERE CREATED_AT <'2012-04-12'
GROUP BY UTM_SOURCE,
         UTM_CAMPAIGN,
         HTTP_REFERER
ORDER BY 4 DESC
;


SELECT COUNT(DISTINCT WEBSITE_SESSION.WEBSITE_SESSION_ID)  AS SESSION, 
COUNT(DISTINCT ORDERS.ORDER_ID) AS ORDERS,
COUNT(DISTINCT ORDERS.ORDER_ID)/COUNT(DISTINCT WEBSITE_SESSION.WEBSITE_SESSION_ID) AS SESSION_TO_ORDER_CONV_RT
FROM WEBSITE_SESSION
LEFT JOIN ORDERS
ON  ORDERS.WEBSITE_SESSION_ID = WEBSITE_SESSION.WEBSITE_SESSION_ID
WHERE WEBSITE_SESSION. UTM_SOURCE='gsearch' 
and WEBSITE_SESSION.CREATED_AT <'2012-04-14'
and WEBSITE_SESSION.UTM_CAMPAIGN ='nonbrand'
;


select 
year(created_at),
week(created_at),
min(date(created_at)) as week_start,
count(distinct website_session_id) as sessions
from website_session
where website_session_id between 100000 and 115000
group by 1,2;


SELECT 
PRIMARY_PRODUCT_ID,

COUNT(CASE WHEN ITEM_PURCHASED = 1 THEN ORDER_ID ELSE NULL END )AS SINGLW_ITEM_ORDER,
COUNT(CASE WHEN ITEM_PURCHASED = 2 THEN ORDER_ID ELSE NULL END )AS TWO_ITEM_ORDER

FROM ORDERS 
WHERE ORDER_ID BETWEEN 31000 AND 32000
GROUP BY 1;



SELECT  
MIN(CREATED_AT) AS WEEK_START_AT,
count(distinct website_session_id) as sessions
FROM WEBSITE_SESSION

WHERE WEBSITE_SESSION. UTM_SOURCE='gsearch' 
and WEBSITE_SESSION.CREATED_AT <'2012-05-12'
and WEBSITE_SESSION.UTM_CAMPAIGN ='nonbrand'
 GROUP BY YEAR(CREATED_AT),
 WEEK(CREATED_AT)

;


SELECT WEBSITE_SESSION.DEVICE_TYPE,
COUNT(DISTINCT WEBSITE_SESSION. WEBSITE_SESSION_ID) AS SESSION,
COUNT(DISTINCT ORDERS.ORDER_ID) AS ORDERS ,
COUNT(DISTINCT ORDERS. ORDER_ID) / COUNT(DISTINCT WEBSITE_SESSION.WEBSITE_SESSION_ID) AS SESSION_TO_ORDER_RT
FROM WEBSITE_SESSION
LEFT JOIN ORDERS 
ON WEBSITE_SESSION.WEBSITE_SESSION_ID= ORDERS.WEBSITE_SESSION_ID
WHERE WEBSITE_SESSION. UTM_SOURCE='gsearch' 
and WEBSITE_SESSION.CREATED_AT <'2012-05-12'
and WEBSITE_SESSION.UTM_CAMPAIGN ='nonbrand'
GROUP BY 1

;


SELECT 
MIN(CREATED_AT) AS WEEK_START_AT,
count(CASE WHEN DEVICE_TYPE='desktop' then  website_session_id ELSE NULL end) as D_sessions,
count(CASE WHEN DEVICE_TYPE='mobile' then  website_session_id ELSE NULL end) as M_sessions

FROM WEBSITE_SESSION

WHERE WEBSITE_SESSION. UTM_SOURCE='gsearch' 
and WEBSITE_SESSION.CREATED_AT <'2012-06-09'
and WEBSITE_SESSION.CREATED_AT >'2012-04-15'
and WEBSITE_SESSION.UTM_CAMPAIGN ='nonbrand'
 GROUP BY YEAR(CREATED_AT),
 WEEK(CREATED_AT)
 ;


